Querians/T-rak

prisma/schema.prisma
create all entities from ERD and fix some PK-FK relationship
add Postgres introspection (@db. ...) (FKs are excluded)
=> feat: create models and add Postgres introspection

app/components/numberInput.jsx, public/addCream.svg, public/minusCream.svg
* create number Input
* max value is 8 and min value is 1
* can use button to increase or decrease
=> feat(create number input)

app/components/tierlistCard.jsx
* create tierlist card for showing in tierlist list in home page
=> feat(create tierlist card)

app/components/imageIcon.jsx, public/arrowDown.svg
* create image frame that have menu popup when clicking
* have delete button inside popup for delete this element by sending function inside
=> Feat(image with menu)

app/components/button.jsx, public/iconLogout.svg, public/iconPlus.svg, public/iconTrash.svg
- create all types of button
- normal button
- Add button
- Delete button
- Logout button
=> Feat(frontend) button component

app/components/addPopup.jsx, public/iconPluscherry.svg
- create plus button that link to popup
- create popup that link to create new element
=> feat(create add element popup)

app/components/searchBox.jsx, public/iconSearchcherry.svg
=> feat(create search box)

app/components/inputbtn.jsx
- create input button with title
=> Feat(frontend) input button

app/(authentication)/tierlist/create/page.jsx, app/(authentication)/tierlist/editdetail/page.jsx, app/components/combobox.jsx, app/components/createtierlist.jsx, app/components/edittierlist.jsx, app/components/inputbtn.jsx, app/components/numberInput.jsx, tailwind.config.js
* merge form page 
* create tierlist
* edit tierlist
=> Feat(frontend create editform) merge to homepage

app/(authentication)/tierlist/edit/[tierListId]/[rowId]/header.jsx, app/(authentication)/tierlist/edit/[tierListId]/[rowId]/page.jsx, app/(authentication)/tierlist/edit/[tierListId]/data.jsx, app/(authentication)/tierlist/edit/[tierListId]/header.jsx, app/(authentication)/tierlist/edit/[tierListId]/page.jsx, app/components/button.jsx, app/components/container.jsx, app/components/elementCard.jsx, app/components/header.jsx, app/components/rowDragable.jsx, app/components/sortableItem.jsx, app/components/spawner.jsx, app/components/tierListRow.jsx, public/dragger.svg, utils/tierList/handler.jsx
- create editExpandPage
- create rowDragable component
- create elementCard component
=> feat(frontend edit expand page)

app/components/spawner.jsx, app/components/tierListRow.jsx, public/iconInputFilebtn.svg
- style add element popup in spawner component
=> style(frontend component spawner) style add element popup

app/(authentication)/tierlist/edit/[tierListId]/[rowId]/header.jsx, app/(authentication)/tierlist/edit/[tierListId]/header.jsx, app/components/spawner.jsx
- adjust style of header in tier list page & edit expand page
-  change Image to Avatar component from next ui
- add tabindex to file input
=> style(frontend tier list page, edit expand page) adjust style in header.jsx & spawner component

app/components/dePopup.jsx, public/iconCheckMark.svg, public/iconTrashDropShadow.svg
- create button that have pop-up 3 styles
- done pop-up
- delete tier list pop-up
- delete tier list row pop-up
=> Feat(frontend pop up) create delete and export pop up

app/components/imputTypeFile.jsx, public/iconInputFilebtn.svg
- create input image button (for testing)
- will update in the future (click add image then button will disappear and replace with image that have edit text)
=> feat(frontend-file-input) : create input file btn

app/components/imputTypeFile.jsx, app/components/inputTypeFile.jsx, public/iconInputFilebtn.svg
- add more features 2 types : 
1. preview : can only see
2. edit : can see and edit
=> Feat(frontend file input) input file

app/api/auth/signup/route.js, app/api/category/route.js, app/api/tierlist/route.js, app/api/tierlist/row/route.js, app/api/tierlist/show/route.js, app/api/user/route.js, prisma/migrations/20231118160848_initial/migration.sql, prisma/schema.prisma
- create delete tierlist api
- create delete row api
- create get category api
- create get all rows in tierlist api
- shift row in tierlist api
- edit get user to return aboutMe
- validate request & manage error of sign up api
=> feat(api) merge to test

app/components/formInput/createtierlist.jsx, app/components/formInput/edittierlist.jsx, app/components/formInput/signUp.jsx
- edit profile page (delete about me)
- add inputTypeFile in create new tier-list
- add inputTypeFile in edit tier-list detail
=> feat(add-profile):add-and-edit-profile

app/(authentication)/profile/page.jsx, app/(authentication)/tierlist/create/page.jsx, app/(authentication)/tierlist/editDetail/[tierListId]/page.jsx, app/components/formInput/createtierlist.jsx, app/components/formInput/edittierlist.jsx, app/components/formInput/profileSetting.jsx, app/components/formInput/signUp.jsx, app/components/inputComponent/combobox.jsx, app/components/inputComponent/numberInput.jsx, app/components/inputTypeFile.jsx, app/signup/page.jsx
- input file can preview
- add name to input
=> feat(frontend edit profile) edit input file

app/api/tierlist/create/route.js
- from creating a new row with a random pastel color,  decided to change to the constant config color
=> fix(api-tierlist): change row color to config color

app/(authentication)/tierlist/edit/[tierListId]/page.jsx, package.json, playwright.config.js, tests/api/tierlist.spec.js, tests/frontend/req.spec.js
* add requirement testing (1-6)
=> test(frontend): requirement testing(1-6)

app/(authentication)/tierlist/edit/[tierListId]/[rowId]/page.jsx, app/api/tierlist/row/route.js
- fix the updated row API to get requests with formData by separate picture and data field
- create a save function on the page to modify the structure of the request before sending it with the API
=> fix(api-tierlistrow): fix picture upload api

tests/frontend/req.spec.js
* update testcase to docs requirement
* some test case need new revision of code
=> test(frontend): add requirement test

app/(authentication)/tierlist/edit/[tierListId]/page.jsx
- change file name to `{Tier-list name}`.jpg
=> feat(frontend-editTierList): change export file name

app/components/dragComponent/sortableItem.jsx, tests/frontend/req.spec.js
=> test(frontend): add requirement testing

tests/api/auth.spec.js, tests/api/category.spec.js, tests/api/tierlist.spec.js, tests/api/user.spec.js, tests/frontend/req.spec.js
*  update assertion in any test case, both backend(API) and frontend testcases
=> fix(test): update test case
